//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thunderbolt
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineService
    {
        public int Id { get; set; }
        public int MachineId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> ActualTime { get; set; }
        public Nullable<System.DateTime> ServiceTime { get; set; }
        public string MachineStatus { get; set; }
        public string UserStatus { get; set; }
        public string CallStatus { get; set; }
        public string CallSid { get; set; }
    }
}
